/* ============================================================================================
   THE GEAR DROP (ruled, the tier pass): every role exists at every tier. A tier-one sniper is
   worse than a tier-four sniper, but there is always a sniper — so that when the Armoury gates
   a young OA to tiers one and two, it is gated to worse kit, not to half a game.

   This tool is run ONCE to write the new models into data/items.json, and is kept so the drop
   is legible and repeatable: every new weapon is built on its type's nearest existing model and
   scaled to its tier; armour and sidearms are authored whole; mods and consumables are RE-TIERED
   rather than invented, because the fight reads consumables by id. Formula prices are
   regenerated by the catalogue's own formula afterwards, as the suite demands.

   node sim/tools/gear_drop.cjs            -> rewrites data/items.json (idempotent: skips ids already present)
   ============================================================================================ */
const fs = require('fs');
const path = require('path');
const FILE = path.join(__dirname, '../../data/items.json');
const data = JSON.parse(fs.readFileSync(FILE, 'utf8'));
const L = data.items;
const have = new Set(L.map(i => i.id));

/* the tier curve: power relative to tier three */
const POW = { 1: 0.75, 2: 0.87, 3: 1.0, 4: 1.25, 5: 1.5 };
/* the tags a plain, early model keeps — what makes the type what it is, and nothing clever */
const PLAIN_TAGS = new Set(['burst', 'area', 'nonlethal', 'single_shot', 'cover_shred']);
/* a type's pen at the top end: heavy guns punch through, the rest barely */
const HEAVY = new Set(['Anti-Materiel', 'Long Rifles', 'Close-Quarters', 'Marksman Rifles']);

function template(type, family, tier) {
  const same = L.filter(i => i.slot === 'primary' && i.type === type);
  const fam = same.filter(i => i.family === family);
  const pool = fam.length ? fam : same;
  return pool.slice().sort((a, b) => Math.abs(a.tier - tier) - Math.abs(b.tier - tier) || (a.tier - b.tier))[0];
}

function weapon(spec) {
  const t = template(spec.type, spec.family, spec.tier);
  const e = JSON.parse(JSON.stringify(t.effects));
  e.power = Math.max(2, Math.round((e.power || 4) * POW[spec.tier] / POW[t.tier]));
  if (spec.tier <= 2) { e.pen = 0; e.tags = (e.tags || []).filter(x => PLAIN_TAGS.has(x)); }
  else if (spec.tier >= 4) e.pen = Math.max(e.pen || 0, HEAVY.has(spec.type) ? spec.tier - 3 : (spec.tier === 5 ? 1 : 0));
  if (spec.tier === 5) e.pen = Math.min(3, e.pen);
  if (spec.family === 'energy' && t.family !== 'energy') {
    e.damage = 'energy'; e.charge = e.mag || 12; e.noise = 1; e.reload = Math.max(2, e.reload || 1);
  } else if (spec.family === 'ballistic' && t.family === 'energy') {
    e.damage = spec.type === 'Launchers' ? 'explosive' : 'ballistic'; delete e.charge; e.noise = 2;
    e.tags = (e.tags || []).filter(x => ['emp', 'disorient', 'burn', 'plasma'].indexOf(x) < 0);
  }
  if (spec.type === 'Stun-Grade') { e.tags = Array.from(new Set(['nonlethal'].concat(e.tags || []))); }
  /* A TIER IS A BETTER GUN, NOT A LOUDER ONE. Power moves a wound's severity by three-quarters of a point
     on a hundred, so the ladder is carried by how a gun handles: steadier in the hand, quicker to the
     shot, a deeper magazine — each tier above the template a step better, each below a step worse. */
  const dt = spec.tier - t.tier;
  e.handling = Math.round((e.handling || 0) + 2 * dt);
  e.snap = Math.max(0, Math.round((e.snap || 0) - dt));
  if (e.mag) e.mag = Math.max(1, Math.round(e.mag * (1 + 0.12 * dt)));
  if (e.charge) e.charge = e.mag;
  const out = { id: spec.id, name: spec.name, category: 'weapon', slot: 'primary', family: spec.family, tier: spec.tier,
                cost: 0, bulk: t.bulk, effects: e, price_model: spec.tier === 5 ? 'scarcity' : 'formula', legality: 'legal',
                identity: spec.identity, type: spec.type };
  if (spec.tier === 5) { out.exotic = true; out.cost = spec.cost; }
  return out;
}

const WEAPONS = [
  /* the gaps: a type missing at a tier */
  { id: 'itm_hunting_longarm',   type: 'Long Rifles',     family: 'ballistic', tier: 2, name: 'Stalker Longarm',        identity: 'Bought for deer. Kept for the long walk across open ground.' },
  { id: 'itm_tallgrass_longarm', type: 'Long Rifles',     family: 'ballistic', tier: 5, name: 'Tallgrass Longarm',      identity: 'Nobody hears it. Nobody who needs to.', cost: 9900 },
  { id: 'itm_deer_rifle',        type: 'Marksman Rifles', family: 'ballistic', tier: 1, name: 'Converted Deer Rifle',   identity: 'A glass sight bolted on by somebody who meant well.' },
  { id: 'itm_warden_dmr',        type: 'Marksman Rifles', family: 'ballistic', tier: 5, name: 'Warden DMR',             identity: 'Every round an argument won at the first word.', cost: 9700 },
  { id: 'itm_hornet_pdw',        type: 'Submachine Guns', family: 'ballistic', tier: 5, name: 'Hornet PDW',             identity: 'A wall of small certainties.', cost: 9600 },
  { id: 'itm_old_squad_gun',     type: 'Support Guns',    family: 'ballistic', tier: 1, name: 'Old Squad Gun',          identity: 'Heavy, loud, and older than the man carrying it.' },
  { id: 'itm_sawn_off',          type: 'Scatterguns',     family: 'ballistic', tier: 1, name: 'Sawn-Off Double',        identity: 'Two barrels, one decision.' },
  { id: 'itm_breacher_auto',     type: 'Scatterguns',     family: 'ballistic', tier: 5, name: 'Breacher Autoshotgun',   identity: 'Empties a room without opening the door.', cost: 9800 },
  { id: 'itm_patrol_carbine',    type: 'Carbines',        family: 'ballistic', tier: 1, name: 'Patrol Carbine',         identity: 'Short, light, and forgiving of cold hands.' },
  { id: 'itm_folding_carbine',   type: 'Carbines',        family: 'ballistic', tier: 2, name: 'Folding-Stock Carbine',  identity: 'Fits in a pack. Unfolds into a problem.' },
  { id: 'itm_pathfinder_carbine',type: 'Carbines',        family: 'ballistic', tier: 5, name: 'Pathfinder Carbine',     identity: 'Built for the first squad down and the last one out.', cost: 9500 },
  { id: 'itm_rocket_tube',       type: 'Launchers',       family: 'ballistic', tier: 1, name: 'Improvised Rocket Tube', identity: 'Pipe, fuse, and faith.' },
  { id: 'itm_rifle_grenadier',   type: 'Launchers',       family: 'ballistic', tier: 2, name: 'Rifle-Grenade Launcher', identity: 'Lobs a problem over the wall they are hiding behind.' },
  { id: 'itm_drum_launcher',     type: 'Launchers',       family: 'ballistic', tier: 3, name: 'Drum Launcher',          identity: 'Six rounds of bad news, one after another.' },
  { id: 'itm_elephant_gun',      type: 'Anti-Materiel',   family: 'ballistic', tier: 1, name: 'Elephant Gun',           identity: 'Kicks like the thing it was made for.' },
  { id: 'itm_salvaged_atr',      type: 'Anti-Materiel',   family: 'ballistic', tier: 2, name: 'Salvaged Anti-Tank Rifle', identity: 'Pulled off a wreck. Still finds armour through the smoke.' },
  { id: 'itm_breaker_rifle',     type: 'Anti-Materiel',   family: 'ballistic', tier: 3, name: 'Breaker Rifle',          identity: 'Opens cover the way a key opens a door.' },
  { id: 'itm_trench_pump',       type: 'Close-Quarters',  family: 'ballistic', tier: 1, name: 'Trench Pump',            identity: 'For the last three metres of any argument.' },
  { id: 'itm_room_clearer',      type: 'Close-Quarters',  family: 'ballistic', tier: 2, name: 'Room Clearer',           identity: 'Short barrel. Short conversation.' },
  { id: 'itm_siege_breacher',    type: 'Close-Quarters',  family: 'ballistic', tier: 5, name: 'Siege Breacher',         identity: 'The door is the wall now.', cost: 9900 },
  { id: 'itm_prod_gun',          type: 'Stun-Grade',      family: 'energy',    tier: 1, name: 'Prod Gun',               identity: 'Cattle took it badly. People take it worse.' },
  { id: 'itm_tether_stunner',    type: 'Stun-Grade',      family: 'energy',    tier: 4, name: 'Tether Stunner',         identity: 'Puts them down and keeps them down.' },
  { id: 'itm_quietus_projector', type: 'Stun-Grade',      family: 'energy',    tier: 5, name: 'Quietus Projector',      identity: 'A whole squad asleep in the grass, and not a mark on them.', cost: 9500 },
  /* energy reaches down and up: something to aim at every tier */
  { id: 'itm_lumen_rifle',       type: 'Assault Rifles',  family: 'energy',    tier: 2, name: 'Lumen Rifle',            identity: 'A training beam somebody turned up past the stop.' },
  { id: 'itm_spark_repeater',    type: 'Submachine Guns', family: 'energy',    tier: 2, name: 'Spark Repeater',         identity: 'Chatters, crackles, and burns through a cell in a breath.' },
  { id: 'itm_glint_rifle',       type: 'Marksman Rifles', family: 'energy',    tier: 3, name: 'Glint Rifle',            identity: 'The first thing they see is the last thing they see.' },
  { id: 'itm_starfall_carbine',  type: 'Carbines',        family: 'energy',    tier: 5, name: 'Starfall Carbine',       identity: 'Every shot a little sunrise.', cost: 10200 },
  { id: 'itm_horizon_lance',     type: 'Long Rifles',     family: 'energy',    tier: 5, name: 'Horizon Lance',          identity: 'Reaches the ridge line before the sound does.', cost: 10400 },
  { id: 'itm_sunforge_repeater', type: 'Support Guns',    family: 'energy',    tier: 5, name: 'Sunforge Repeater',      identity: 'Holds a line of light across the whole field.', cost: 10600 }
];

/* armour, authored whole: the roles at the tiers that lacked them */
const ARMOUR = [
  { id: 'itm_foil_poncho',    name: 'Foil Poncho',      tier: 1, bulk: 1, effects: { protection: 1, mobility: 1, tags: [], resist: { ballistic: -1, energy: 1, explosive: 0 }, covers: ['torso', 'arms'] }, identity: 'Crinkles when you run. Turns a beam, sometimes.' },
  { id: 'itm_sandbag_vest',   name: 'Sandbag Vest',     tier: 1, bulk: 3, effects: { protection: 1, mobility: -1, tags: [], resist: { ballistic: 0, energy: -1, explosive: 2 }, covers: ['torso'] }, identity: 'Exactly what it sounds like.' },
  { id: 'itm_trauma_plates',  name: 'Trauma Plates',    tier: 2, bulk: 2, effects: { protection: 3, mobility: 0, tags: [], resist: { ballistic: 2, energy: -1, explosive: 0 }, covers: ['torso'] }, identity: 'Stops the round. Not the bruise.' },
  { id: 'itm_patrol_vest',    name: 'Patrol Vest',      tier: 2, bulk: 2, effects: { protection: 2, mobility: 0, tags: [], resist: { ballistic: 1, energy: 1, explosive: 0 }, covers: ['torso', 'arms'] }, identity: 'Good at nothing in particular, which is often enough.' },
  { id: 'itm_prism_shell',    name: 'Prism Shell',      tier: 5, bulk: 3, effects: { protection: 7, mobility: 0, tags: [], resist: { ballistic: 0, energy: 3, explosive: 0 }, covers: ['torso', 'head', 'arms'] }, identity: 'Light goes in. Light comes out somewhere else.' },
  { id: 'itm_bastion_plate',  name: 'Bastion Plate',    tier: 5, bulk: 4, effects: { protection: 7, mobility: -1, tags: [], resist: { ballistic: 3, energy: 0, explosive: 1 }, covers: ['torso', 'head', 'legs'] }, identity: 'Walks through small-arms fire like weather.' }
];
const SIDEARMS = [
  { id: 'itm_spark_pistol',   name: 'Spark Pistol',       tier: 2, family: 'energy',    tpl: 'itm_las_sidearm', power: 2, identity: 'A torch that bites.' },
  { id: 'itm_magnum_auto',    name: 'Magnum Autoloader',  tier: 4, family: 'ballistic', tpl: 'itm_service_pistol', power: 4, identity: 'The last word, repeated.' },
  { id: 'itm_duelist_needler',name: 'Duelist’s Needler', tier: 5, family: 'ballistic', tpl: 'itm_service_pistol', power: 4, identity: 'Made for one person, and for one moment.' }
];
/* re-tiered, not invented: the fight reads these by id */
const RETIER = {
  itm_medkit: 1, itm_smoke_canister: 1, itm_ammo_satchel: 1, itm_frag_grenade: 2, itm_stim_shot: 2, itm_power_cell: 2,
  itm_auto_turret: 4
};
const MOD_TIER = { 'Bipod': 2, 'Lightweight Frame': 2, 'Broadcast Tag': 2, 'Extended Magazine': 2, 'Recoil Compensator': 2, 'Beam Diffuser': 2,
                   'Target Link': 4, 'Suppressor': 4, 'AP Rounds': 4, 'Incendiary Loads': 4, 'Focusing Array': 5 };

let added = 0;
const fresh = new Set();
for (const w of WEAPONS) if (!have.has(w.id)) { L.push(weapon(w)); fresh.add(w.id); added++; }
for (const a of ARMOUR) if (!have.has(a.id)) {
  L.push({ id: a.id, name: a.name, category: 'armor', slot: 'armor', tier: a.tier, cost: 0, bulk: a.bulk, effects: a.effects,
           price_model: 'formula', legality: 'legal', identity: a.identity }); added++;
}
for (const s of SIDEARMS) if (!have.has(s.id)) {
  const t = L.find(i => i.id === s.tpl);
  const e = JSON.parse(JSON.stringify(t.effects)); e.power = s.power;
  if (s.tier >= 4) e.pen = 1;
  L.push({ id: s.id, name: s.name, category: 'weapon', slot: 'sidearm', family: s.family, tier: s.tier, cost: 0, bulk: 1, effects: e,
           price_model: 'formula', legality: 'legal', identity: s.identity, type: 'Sidearms' }); added++;
}
let moved = 0;
for (const it of L) {
  if (it.slot === 'consumable' && RETIER[it.id] != null && it.tier !== RETIER[it.id]) { it.tier = RETIER[it.id]; moved++; }
  if (it.slot === 'mod' && MOD_TIER[it.name] != null && it.tier !== MOD_TIER[it.name]) { it.tier = MOD_TIER[it.name]; moved++; }
}
/* three models the ladder measured level with the tier below get a further step of handling (measured, not guessed) */
for (const id of ['itm_drum_launcher', 'itm_tether_stunner', 'itm_starfall_carbine']) {
  const it = L.find(i => i.id === id); if (it && fresh.has(id)) { it.effects.handling += 2; it.effects.snap = Math.max(0, it.effects.snap - 1); }
}
/* prices from the catalogue's own formula */
const I = require('../items.js');
let priced = 0;
for (const it of L) if (it.price_model === 'formula') { const c = I.formulaCost(it); if (c !== it.cost) { it.cost = c; priced++; } }
fs.writeFileSync(FILE, JSON.stringify(data, null, 1) + '\n');
console.log('added', added, 'retiered', moved, 'repriced', priced, 'total', L.length);
